feat: Add type of asset bump in the IndexesUpdateAssetHistory entity
decentraland/rentals-graph pull request #17
Opened 2022-10-31 14:58 UTC by juanmahidalgo

Closes #16

2022-10-31 15:01 UTC, fzavalia commented on schema.graphql
> +enum IndexUpdateEventType @entity {
You can remove the @entity on an enum I believe

2022-10-31 15:05 UTC, fzavalia commented on src/handlers/rentals.ts
> +  let assetNonceUpdateHistoryIdDueToRent = getIndexesUpdatesHistoryNextCount().value.minus(BigInt.fromI32(1))
You should do this for the last 2 asset index updates, not just the last one

2022-10-31 17:03 UTC, fzavalia approved these changes

2022-10-31 18:31 UTC, LautaroPetaccio requested changes

2022-10-31 18:31 UTC, LautaroPetaccio commented on src/handlers/rentals.ts
> +  let lastAssetNonceUpdateHistoryId = getIndexesUpdatesHistoryNextCount().value.minus(BigInt.fromI32(1))
`getAssetIndexesUpdatesHistoryCount` is the function that you're looking for here.

2022-10-31 18:31 UTC, LautaroPetaccio commented on src/handlers/rentals.ts
> +  let lastAssetNonceUpdateHistoryId = getIndexesUpdatesHistoryNextCount().value.minus(BigInt.fromI32(1))
`getAssetIndexesUpdatesHistoryCount` returns the index of the next `AssetNonceUpdateHistory`. Taking into consideration that the event to increase the nonce has already been processed, the current index is the one that you would like to set. The previous indexes might not be relevant or might not exist as the index 0 is not generated through an event, but the number 1 is. If you want the previous index to be set, be aware to check individually for its existence as the current if will not set the index as `RENT` if the other one doesn't exist.
You can use `getAssetIndexesUpdatesHistoryCount` to get the current index.

2022-11-01 12:53 UTC, LautaroPetaccio commented on src/handlers/rentals.ts
> +  let lastAssetNonceUpdateHistoryId = getIndexesUpdatesHistoryNextCount().value.minus(BigInt.fromI32(1))
After re-reviewing the code, you were right. The `getIndexesUpdatesHistoryCount` is the function to use. The other indexes are related to the entity type that is described in their parent entity, the index history entity.

2022-11-01 12:54 UTC, LautaroPetaccio approved these changes

2022-11-16 13:19 UTC, merged